spring:
  datasource:
    url: jdbc:mysql://192.168.75.128:3306/lava?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8

    #≈‰÷√ Jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true